### ISSUE TITLE
Class OC L10n not found

### ISSUE THREAD

**Issue by glannes31** [CNRS-DSI-Dev/user_files_migrate#7]
Bonjour,

Sur plusieurs instances  de partage-dev , nous avons des problèmes avec OC_l10n empechant la migration de se lancer.

20170307_081907 Migration request #2: from uid "mycore.jmeter"" to uid "mycore.jmeter@cnrs.fr"
An unhandled exception has been thrown:
Error: Class 'OC_L10N' not found in /var/www/mycore_ppa2/apps/user_files_migrate/service/mailservice.php:191
Stack trace:
#0 /var/www/mycore_ppa2/apps/user_files_migrate/service/mailservice.php(40): OCA\User_Files_Migrate\Service\MailService->getUserLanguage('mycore.jmeter')
#1 /var/www/mycore_ppa2/apps/user_files_migrate/command/migrate.php(133): OCA\User_Files_Migrate\Service\MailService->mailUser('mycore.jmeter', 'mycore.jmeter@c...')
#2 /var/www/mycore_ppa2/apps/user_files_migrate/command/migrate.php(65): OCA\User_Files_Migrate\Command\Migrate->processMigration()
#3 /var/www/mycore_ppa2/lib/composer/symfony/console/Command/Command.php(256): OCA\User_Files_Migrate\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/mycore_ppa2/lib/composer/symfony/console/Application.php(818): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/mycore_ppa2/lib/composer/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(OCA\User_Files_Migrate\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/mycore_ppa2/lib/composer/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/mycore_ppa2/lib/private/Console/Application.php(158): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/mycore_ppa2/console.php(99): OC\Console\Application->run()
#9 /var/www/mycore_ppa2/occ(11): require_once('/var/www/mycore...')
#10 {main}[root@owncloud mycore_ppa2]# cd ..

Sur mon instance:

[root@owncloud mycore_gll]# su -s /bin/sh apache -c '/opt/remi/php70/root/usr/bin/php ./occ user_files_migrate:migrate'
20170307_084139 Beginning migration
20170307_084139 Migration request #1: from uid "mycore.jmeter"" to uid "mycore.jmeter@cnrs.fr"

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'OC_L10N' not found

user_files_migrate:migrate [-l|--list]

**Comment by ppaysant** [comment]
Hello

Thx for your interest :)
OC changes L10N process, I must check that. Hope to be able to do that soon !

Regards

**Comment by glannes31** [comment]
Patrick, il me semble qu'on avait parle ensemble à l'oral  et que t'avais modifié un fichier . Oui c'est guillaume du support ;-)
